### ISSUE TITLE
circle segments and rotation

### ISSUE THREAD

**Issue by ecrax** [nichilum/tlm-demo-rs#52]

**Comment by JonathanKr** [comment]
implemented in 9583a504031d21f487c5bc544df348710963d294

might need a rotation value

**Comment by JonathanKr** [comment]
rotation was implemented in 0a7829a8b82f78ee2f07e7c4eadf882489775ccd

we need to think about filled walls

**Comment by JonathanKr** [comment]
fully implemented in da1d9cf98af3a45a397d8f954952fecefd2e09d7
